baseurl: /bogota
permalink: pretty
markdown: kramdown
paginate: 5
repo: bogota
github_org: maptime
maptime:
  chapter: MaptimeBogotá
  twitter: MaptimeBogota
  disqus: maptimebogota

future: true
gems:
  - jekyll-feed
